### ISSUE TITLE
NT Core Errors

### ISSUE THREAD

**Issue by kjm16216** [FRO5401/Pulsatrix#2]
When run in eclipse, Win10 laptop
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no ntcore in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at edu.wpi.first.wpilibj.networktables.NetworkTablesJNI.<clinit>(NetworkTablesJNI.java:59)
	at edu.wpi.first.wpilibj.networktables.NetworkTable.initialize(NetworkTable.java:46)
	at edu.wpi.first.wpilibj.networktables.NetworkTable.getTable(NetworkTable.java:213)
	at Webcam.main(Webcam.java:41)`

**Comment by kjm16216** [comment]
https://www.chiefdelphi.com/forums/showthread.php?t=141928&highlight=UnsatisfiedLinkError%3A+no+ntcore+in+java.library.path

**Comment by kjm16216** [comment]
https://www.chiefdelphi.com/forums/showthread.php?t=141749

**Comment by kjm16216** [comment]
https://www.chiefdelphi.com/forums/showthread.php?t=141928&highlight=UnsatisfiedLinkError%3A+no+ntcore+in+java.library.path

**Comment by kjm16216** [comment]
https://www.reddit.com/r/FRC/comments/5ngf85/can_someone_eli5_network_tables/

**Comment by kjm16216** [comment]
Grab the desktop version of this... and maybe the windows ones.  And the arm ones might be needed for the pi.
http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/wpilib/networktables/java/NetworkTables/3.1.5/

**Comment by kjm16216** [comment]
From Laura:
If you are still interested, I was saying that you need to include the windows network table libraries in your eclipse project build path. This way it compiles correctly when you create a .jar file. The .jar file will then need to use the native linux libraries when it runs on the pi. 

To get the network tables in eclipse you can right click on the project then go to build path > configure build path. Then in the libraries tab you can "Add External Jar" and add the "NetworkTables" and "NetworkTables-Source" jars. These are found in "C:\Users\{UserName}\wpilib\java\current\lib"
