### ISSUE TITLE
Error on Pi

### ISSUE THREAD

**Issue by kjm16216** [FRO5401/Pulsatrix#3]
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.Error: Unresolved compilation problem:
        Duplicate local variable pr

        at Webcam.main(Webcam.java:22)
`

**Comment by kjm16216** [comment]
https://www.chiefdelphi.com/forums/showthread.php?t=141928&highlight=UnsatisfiedLinkError%3A+no+ntcore+in+java.library.path

**Comment by kjm16216** [comment]
https://www.reddit.com/r/FRC/comments/5ngf85/can_someone_eli5_network_tables/

**Comment by kjm16216** [comment]
Source for sample images
https://usfirst.collab.net/sf/go/projects.wpilib/frs.sample_programs.2017_c_java_vision_sample

**Comment by kjm16216** [comment]
Commented out the try/catch and the sleep block. Error went away, replaced by error similar to #2
